name: Update ETF Data

on:
  schedule:
    - cron: '0 6 * * *' # codziennie o 6:00 UTC (8:00 w Polsce)
  workflow_dispatch: # możliwość ręcznego uruchomienia

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas python-dateutil

      - name: Run ETF script
        run: python scripts/gem.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/results.json public/data/history.json
          git commit -m "Automatic data update" || echo "No changes"
          git push
